version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout

      - run: |
          cd eval && docker build -t "attngan" -f dockerfile.cpu .

      - run:
          name: run the container
          background: true
          command: |
            docker run -it -e BLOB_KEY="$BLOB_KEY" -e TELEMETRY="$TELEMETRY_KEY" -p 5678:8080 attngan

      - run: sleep 100